export const chars = {
    double: {
        cs: 7,
        // dz: -1,
        // dzs: -1,
        gy: 4,
        ly: 8,
        ny: 5,
        ty: 10,
        sz: 3,
        zs: 8,
    },
    single: {
        a: 1,
        á: 1,
        b: 2,
        c: 5,
        d: 2,
        e: 1,
        é: 3,
        f: 4,
        g: 2,
        h: 3,
        i: 1,
        í: 5,
        j: 4,
        k: 1,
        l: 1,
        m: 1,
        n: 1,
        o: 1,
        ó: 2,
        ö: 4,
        ő: 7,
        p: 4,
        // q: -1,
        r: 1,
        s: 1,
        t: 1,
        u: 4,
        ú: 7,
        ü: 4,
        ű: 7,
        v: 3,
        // w: -1,
        // x: -1,
        // y: -1,
        z: 4,
    },
} as const;
